### ISSUE TITLE
賃貸住宅の相場予測

### ISSUE THREAD

**Issue by geeknees** [nendworks/deepbook#4]
# 目的・やれること
- 賃貸住宅の相場予測
- 引越時、良さそうな物件が見つかったとして、その家賃が相場とどの程度離れているか判断する

# 背景
- 機械学習の基本である線形回帰（linear regression）の独立変数が2つ以上のサンプル
- ディープラーニングは使用しない

# 対象者
- 例：機械学習の基本である線形回帰の応用例を学びたい人

## 手順および想定所要時間
1. 30 ~ 60 min データの収集（スクレーパーの実装）
1. 60 min ~ データ加工
1. 60 min ~ 学習モデルの作成 / 精度測定
1. 60 min ~ 予測させる
 
## データの集め方
- 住宅情報を掲載しているサイトから、負荷をかけない形で入手する
```
scrapy crawl suumo_shibuya -o result.csv
```

## 追加で必要なライブラリ等
- あれば

## 関連URL
- 他にやっている人の記事など。あれば

**Comment by kiyo-e** [comment]
Rだけど、こういうのかな

http://www.slideshare.net/berobero11/lt-40565180
http://megalodon.jp/2014-0608-1632-37/heartruptcy.blog.fc2.com/blog-entry-153.html

**Comment by geeknees** [comment]
参考になる！線形回帰は項目数の調整はあるけど、比較的パラメーター調整は不要なので、例題を一つやってみたいというのが目的。あとは2年以内に引越す予定なので、参考になれば良いな程度。

**Comment by kiyo-e** [comment]
これいいね！
普通に俺もほしいし、欲しい人多そうだし、何よりお金の匂いもするｗ
てか、当時この記事見たときに作ろうとしたけど、よくわからなくてやめた記憶がある。

今年引っ越す予定だから、あるといいなあ。
