### ISSUE TITLE
ユニクロ検知

### ISSUE THREAD

**Issue by geeknees** [nendworks/deepbook#5]
# 目的・やれること
- 人の写真を登録するとユニクロを着用しているか判定する

# 背景
- ディープラーニングの代表的なアルゴリズムの一つである畳み込みニューラルネットワーク（CNN）を使って実装する

# 対象者
- Tensorflowと使って実際の応用例を試してみたい人
- ディープラーニング×画像をつかって何ができるか理解したい人

## 手順および想定所要時間
1. 30 ~ 60 min データの収集
1. 10 min ~ データ加工
1. 60 min ~ 学習モデルの作成 / 精度測定
1. 60 min ~ 予測させる

## データの集め方
- ユニクロ公式サイトから負荷をかけない形で収集する
http://www.uniqlo.com/jp/stylingbook/pc/
- 画像サイズを最適化する

## 追加で必要なライブラリ等
- casperjs
- Tensorflow

## 関連URL
- 他にやっている人の記事など。あれば

### 1.  casperjsの準備
npmがインストールされている状態で
```
npm install casperjs
```
もしくは
```
yarn add casperjs
```

### 2.  データ収集スクリプトの実行
https://github.com/nendworks/deepbook/blob/master/vol1/1/3/scrape_uni.js
```
casperjs scrape_uni.js
```
https://github.com/nendworks/deepbook/blob/master/vol1/1/3/scrape_ware.js
```
casperjs scrape_ware.js
```

### 3.  データの加工
macであれば画像ディレクトリで下記を実行
```
sips -Z 160 *.jpg
```

**Comment by kiyo-e** [comment]
これは面白い！
